# Uses the 32 most common elements in PUBCHEM + "ukn" token
max_size: 32
valid_atomic_nums: [6, 8, 7, 17, 16, 9, 35, 15, 53, 14, 11, 33, 80, 50, 5, 20, 19, 30, 26, 34, 13, 29, 12, 82, 24, 27, 28, 56, 78, 25, 52, "ukn"]
valid_bond_types: ["SINGLE", "DOUBLE", "TRIPLE", "AROMATIC", "ukn"]
